### ISSUE TITLE
We have to vote with all the tokens staked, we can't choose a quantity.

### ISSUE THREAD

**Issue by aurerum** [VitaDAO/VitaDAO-web3#47]
**Is your feature request related to a problem? Please describe.**
We have to vote with all the tokens staked, we can't choose a quantity.

![voting page](https://user-images.githubusercontent.com/80455782/125191626-b5759400-e243-11eb-823d-5ed1e2694577.JPG)

**Comment by audieleon** [comment]
This is by design. Your staked tokens are your "voting power" for all the proposals you wish to vote on. So if you stake 100 tokens and vote on proposal 1, you will vote 100 on proposal 1, which can't be changed. If you stake another 300 for proposal 2, you will have a voting power of 400 for that vote. When proposal 3 comes around, you will still have a voting power of 400 for proposal 3.  The voting power is not diminished by the number of active proposals, you aren't "spending" tokens to vote. 

If you wish to see a more complex voting mechanism, we'll be starting on v1.1 (maintenance) and v2.0 (evolution) immediately after the mainnet launch push. We'll be using discussions to create the requirements.
