### ISSUE TITLE
I can approve already approved tokens

### ISSUE THREAD

**Issue by aurerum** [VitaDAO/VitaDAO-web3#74]
In this example, I can approve 150 tokens that are already approved. (I have just those 150 tokens in my wallet.).
If I approve again 150 tokens, according to the UI that doesn't increase my approved token "balance".
In other words, that approve 0 tokens.

The "approve" button should be deactivated when the tokens are already approved

Maybe It is better to do an unlimited approval on click on the approve button.
Another possibility is to leave the choice to the user between unlimited approval or a certain quantity of tokens.

**Screenshots**
![Can approve with 0 token in balanceunlock date wtf](https://user-images.githubusercontent.com/80455782/127752420-e8d82f8e-5dbb-4730-b104-e646a5b09d8c.JPG)

**Comment by audieleon** [comment]
This is an issue with ERC20 in general. The amount you approve has nothing to do with your balance, or even the amount of VITA available to stake. If you approve more tokens, then more will be approved. We may be able to benefit from an explainer in context here, but there's nothing we can do about this behavior because it's correct on chain. 

For example. I could, as a user, decide today to pay the gas once and approve all VITA I think I'll _ever_ have, or I could approve only my current balance and need to approve more tomorrow when I get my incentive for some work I've done for the DAO. (Along with the gas to approve twice.)  _In either case_, I am still free to approve _more_ VITA, even immediately after I approve.

**Comment by aurerum** [comment]
Yes, I understand this but the problem here is that even if I approve more tokens, the approved tokens are still 150 tokens.
One thing that you can do is to approve unlimited tokens on click on the approval button, like that it solves all the problems.
Are you the solidity and web 3 developer?
